# Generated by Django 5.2.10 on 2026-01-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_over',
        ),
        migrations.AlterField(
            model_name='game',
            name='room_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
